
// export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN"
// export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
// export const SETUP_USER_ERROR = "SETUP_USER_ERROR"


export const LOGOUT_USER = " LOGOUT_USER"

export const HANDLE_CHANGE = " HANDLE_CHANGE"


export const CLEAR_VALUES = " CLEAR_VALUES"

export const CREATE_TODO_BEGIN = " CREATE_TODO_BEGIN"
export const CREATE_TODO_SUCCESS = "  CREATE_TODO_SUCCESS"
export const CREATE_TODO_ERROR = "  CREATE_TODO_ERROR"

export const GET_TODOS_BEGIN = 'GET_TODOS_BEGIN';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';

export const SET_EDIT_TODO = 'SET_EDIT_TODO'


export const EDIT_TODO_BEGIN = 'EDIT_TODO_BEGIN';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_ERROR = 'EDIT_TODO_ERROR';

export const DELETE_TODO_BEGIN = 'DELETE_TODO_BEGIN';
export const DELETE_TODO_ERROR = ' DELETE_TODO_ERROR';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';













